Kamala Eye Clinic/Models/StockLedger.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kamala_Eye_Clinic.Models
{
    public class StockLedger
    {
        public int hid { get; set; }
        public int transactionid { get; set; }
        public int itemid { get; set; }

        [Required]
        [Display(Name ="Item Name:")]
        public string itemname { get; set; }

        [Required]
        [Display(Name = "Unit:")]
        public string unit { get; set; }

        [Required]
        [Display(Name = "Quantity:")]
        public int qty { get; set; }

        [Required]
        [Display(Name = "Type:")]
        public string type { get; set; }

        [Required]
        [Display(Name = "Opening Quantity:")]
        public int openingqty { get; set; }

        [Required]
        [Display(Name = "Closing Quantity:")]
        public int closingqty { get; set; }

        public string createby { get; set; }
        public string updateby { get; set; }
        public string CMD { get; set; }

        public string[] PerformAction()
        {
            try
            {
                this.createby = this.updateby = HttpContext.Current.Session["UserName"].ToString();
                string xml = Common.ToXML(this);
                DBConnection con = new DBConnection();
                System.Data.DataSet ds = con.ExecuteProcedure("SP_StockLedger", xml);
                return Common.CallbackMsg(ds);
            }
            catch (Exception e)
            {
                return new string[] { "Failed", e.Message };
            }
        }

        public StockLedger GetSingleStockItem(int transactionid)
        {
            this.CMD = "View1";
            this.hid = Convert.ToInt32(HttpContext.Current.Session["hospital"]);
            this.transactionid = transactionid;
            string xml = Common.ToXML(this);
            DBConnection con = new DBConnection();
            DataSet ds = con.ExecuteProcedure("SP_StockLedger", xml);
            if (ds != null)
            {
                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    this.itemid = Convert.ToInt32(ds.Tables[0].Rows[i]["itemid"]);
                    this.itemname = ds.Tables[0].Rows[i]["itemname"].ToString();
                    this.unit = ds.Tables[0].Rows[i]["unit"].ToString();
                    this.qty = Convert.ToInt32(ds.Tables[0].Rows[i]["qty"]);
                    this.type =ds.Tables[0].Rows[i]["ttype"].ToString();
                    this.openingqty = Convert.ToInt32(ds.Tables[0].Rows[i]["openingqty"]);
                    this.closingqty = Convert.ToInt32(ds.Tables[0].Rows[i]["closingqty"]);
                }
            }
            return this;
        }

        public List<SelectListItem> units = new List<SelectListItem>();

        public StockLedger getMultipleUnit()
        {
            UOM obj = new UOM();
            obj.CMD = "View";
            obj.hid = Convert.ToInt32(HttpContext.Current.Session["hospital"]);
            string xml = Common.ToXML(obj);
            DBConnection con = new DBConnection();
            DataSet ds = con.ExecuteProcedure("SP_UOM", xml);
            for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
            {
                units.Add(new SelectListItem { Text = ds.Tables[0].Rows[i]["uom"].ToString(), Value = ds.Tables[0].Rows[i]["unitid"].ToString() });
            }
            return this;
        }

        public List<SelectListItem> items = new List<SelectListItem>();

        public StockLedger getMultipleItems()
        {
            ItemMaster obj = new ItemMaster();
            obj.CMD = "View";
            obj.hid = Convert.ToInt32(HttpContext.Current.Session["hospital"]);
            string xml = Common.ToXML(obj);
            DBConnection con = new DBConnection();
            DataSet ds = con.ExecuteProcedure("SP_Item", xml);
            for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
            {
                items.Add(new SelectListItem { Text = ds.Tables[0].Rows[i]["itemname"].ToString(), Value = ds.Tables[0].Rows[i]["itemid"].ToString() });
            }
            return this;
        }

    }
}

Kamala Eye Clinic/Models/UOM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;

namespace Kamala_Eye_Clinic.Models
{
    public class UOM
    {  
        public int hid { get; set; }
        public int unitid { get; set; }

        [Required]
        [Display(Name = "Unit Name:")]
        public string unitname { get; set; }

        [Required]
        [Display(Name = "Unit of Measurement:")]
        public string uom { get; set; }

        public string createby { get; set; }
        public string updateby { get; set; }
        public string CMD { get; set; }

        public string[] PerformAction()
        {
            try
            {
                this.createby = this.updateby = HttpContext.Current.Session["UserName"].ToString();
                string xml = Common.ToXML(this);
                DBConnection con = new DBConnection();
                DataSet ds = con.ExecuteProcedure("SP_UOM", xml);
                return Common.CallbackMsg(ds);
            }
            catch (Exception e)
            {
                return new string[] { "Failed", e.Message };
            }
        }
        public UOM GetSingleUnit(int unitid)
        {
            this.CMD = "View1";
            this.hid = Convert.ToInt32(HttpContext.Current.Session["hospital"]);
            this.unitid = unitid;
            string xml = Common.ToXML(this);
            DBConnection con = new DBConnection();
            DataSet ds = con.ExecuteProcedure("SP_UOM", xml);
            if (ds != null)
            {
                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    this.unitname = ds.Tables[0].Rows[i]["unitname"].ToString();
                    this.uom = ds.Tables[0].Rows[i]["uom"].ToString();
                }
            }
            return this;
        }
    }
}

Kamala Eye Clinic/Controllers/StockManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kamala_Eye_Clinic.Models;
using System.Data;

namespace Kamala_Eye_Clinic.Controllers
{
    [Sessionclass]
    public class StockManagementController : Controller
    {
        public ActionResult StockLedger()
        {
            StockLedger obj = new Models.StockLedger();
            obj.getMultipleItems();
            obj.getMultipleUnit();
            return View(obj);
        }

        public ViewResult StockLedgerUpdate(int treatmentid)
        {
            StockLedger obj = new Models.StockLedger();

            if (treatmentid > 0)
            {
                obj.CMD = "Update";
                obj = obj.GetSingleStockItem(treatmentid);
                obj.getMultipleItems();
                obj.getMultipleUnit();
            }
            return View("StockLedger", obj);
        }

        [HttpPost]
        public ActionResult StockLedgerUpdate(StockLedger obj, string SubmitBtn)
        {
            StockLedger(obj, SubmitBtn);
            if (SubmitBtn == "Delete")
                return Redirect("~/StockManagement/ViewStockLeader");
            return View("StockLeader", obj);
        }

        [HttpPost]
        public ActionResult StockLedger(StockLedger obj, string SubmitBtn)
        {
            obj.CMD = SubmitBtn == "Save" ? "Save" : SubmitBtn == "Update" ? "Update" : "Delete";
            obj.hid = Convert.ToInt32(Session["hospital"].ToString());
            obj.getMultipleItems();
            obj.getMultipleUnit();
            switch (obj.CMD)
            {
                case "Save":
                    obj.hid = Convert.ToInt32(Session["hospital"].ToString());
                    string[] str = obj.PerformAction();
                    ViewBag.msg = str[1];                   
                    return View("StockLedger", obj);
                case "Update":
                    string[] str1 = obj.PerformAction();
                    ViewBag.msg = str1[2];                  
                    return View("StockLedger", obj);
                case "Delete":
                    string[] str2 = obj.PerformAction();
                    ViewBag.msg = str2[3];                 
                    return View("StockLedger", obj);
                default:
                    return View(obj);
            }
        }

        public ActionResult ViewStockLeader()
        {
            StockLedger obj = new Models.StockLedger();
            DBConnection cn = new DBConnection();
            obj.CMD = "View";
            obj.hid = Convert.ToInt32(Session["hospital"].ToString());
            string xml = Common.ToXML(obj);
            DataSet dataset = cn.ExecuteProcedure("SP_StockLedger", xml);
            return View(dataset);
        }


        /***************************************** Item Master *****************************************/

        public ActionResult Item()
        {
            ItemMaster obj = new Models.ItemMaster();
            obj.getMultipleUnit();
            return View(obj);
        }

        public ViewResult ItemUpdate(int itemid)
        {
            ItemMaster obj = new Models.ItemMaster();

            if (itemid > 0)
            {
                obj.CMD = "Update";
                obj = obj.GetSingleItem(itemid);
                obj.getMultipleUnit();
            }
            return View("Item", obj);
        }

        [HttpPost]
        public ActionResult ItemUpdate(ItemMaster obj, string SubmitBtn)
        {
            Item(obj, SubmitBtn);
            if (SubmitBtn == "Delete")
            return Redirect("~/StockManagement/ViewItem");
            return View("Item", obj);
        }

        [HttpPost]
        public ActionResult Item(ItemMaster obj, string SubmitBtn)
        {
            obj.CMD = SubmitBtn == "Save" ? "Save" : SubmitBtn == "Update" ? "Update" : "Delete";
            obj.hid = Convert.ToInt32(Session["hospital"].ToString());
            switch (obj.CMD)
            {
                case "Save":
                    obj.hid = Convert.ToInt32(Session["hospital"].ToString());
                    string[] str = obj.PerformAction();
                    ViewBag.msg = str[1];
                    obj.getMultipleUnit();
                    return View("Item", obj);
                case "Update":
                    string[] str1 = obj.PerformAction();
                    ViewBag.msg = str1[2];
                    obj.getMultipleUnit();
                    return View("Item", obj);
                case "Delete":
                    string[] str2 = obj.PerformAction();
                    ViewBag.msg = str2[3];
                    obj.getMultipleUnit();
                    return View("Item", obj);
                default:
                    return View(obj);
            }
        }

        public ActionResult ViewItem()
        {
            ItemMaster obj = new Models.ItemMaster();
            DBConnection cn = new DBConnection();
            obj.CMD = "View";
            obj.hid = Convert.ToInt32(Session["hospital"].ToString());
            string xml = Common.ToXML(obj);
            DataSet dataset = cn.ExecuteProcedure("SP_Item", xml);
            return View(dataset);
        }



        /***********************************  UOM ***********************************************/
        public ActionResult UOM()
        {
            UOM obj = new Models.UOM();           
            return View(obj);
        }

        public ViewResult Update(int unitid)
        {
            UOM obj = new Models.UOM();

            if (unitid > 0)
            {
                obj.CMD = "Update";
                obj = obj.GetSingleUnit(unitid);

            }
            return View("UOM", obj);
        }
        [HttpPost]
        public ActionResult Update(UOM obj, string SubmitBtn)
        {
            UOM(obj, SubmitBtn);
            if (SubmitBtn == "Delete") return Redirect("~/StockManagement/UOMView");
            return View("UOM", obj);
        }

        [HttpPost]
        public ActionResult UOM(UOM obj, string SubmitBtn)
        {
            obj.CMD = SubmitBtn == "Save" ? "Save" : SubmitBtn == "Update" ? "Update" : "Delete";
            obj.hid = Convert.ToInt32(Session["hospital"].ToString());
            switch (obj.CMD)
            {
                case "Save":
                    obj.hid = Convert.ToInt32(Session["hospital"].ToString());
                    string[] str = obj.PerformAction();
                    ViewBag.msg = str[1];
                    return View("UOM", obj);
                case "Update":
                    string[] str1 = obj.PerformAction();
                    ViewBag.msg = str1[2];
                    return View("UOM", obj);
                case "Delete":
                    string[] str2 = obj.PerformAction();
                    ViewBag.msg = str2[3];
                    return View("UOM", obj);
                default:
                    return View(obj);
            }

        }

        public ActionResult ViewUOM()
        {
            UOM obj = new Models.UOM();
            DBConnection cn = new DBConnection();
            obj.CMD = "View";
            obj.hid = Convert.ToInt32(Session["hospital"].ToString());
            string xml = Common.ToXML(obj);
            DataSet dataset = cn.ExecuteProcedure("SP_UOM", xml);
            return View(dataset);
        }

    }
}

Kamala Eye Clinic/Views/StockManagement/Item.cshtml
@model Kamala_Eye_Clinic.Models.ItemMaster

@{
    ViewBag.Title = "Item";
    Layout = "~/Views/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-12 form-group">
                <div class="col-md-4">
                    <div class="col-md-5">
                        @Html.LabelFor(model => model.itemname, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.itemname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.itemname, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="col-md-5">
                        @Html.LabelFor(model => model.unit, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-7">
                        @Html.DropDownListFor(model => model.unit,Model.units ,new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.unit, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="col-md-5">
                        @Html.LabelFor(model => model.rate, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.rate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.rate, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-sm-12 form-group" align="center">
                <hr />
                @Html.HiddenFor(model => model.CMD)
                @if (Model.CMD == null)
                {
                    <input type="submit" class="btn btn-default btn-info " value="Save" name="SubmitBtn" />
                }
                else
                {
                    <input type="submit" class="btn btn-default btn-primary " value="Update" name="SubmitBtn" />
                    @* <input type="submit" class="btn btn-default btn-danger" value="Delete" name="SubmitBtn" />*@
                }
                <input type="reset" class="btn btn-warning " value="Reset" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("  Back to List", "ViewItem", "StockManagement", new { @class = "fa fa-arrow-circle-o-left btn btn-info btn-sm" })
</div>

Kamala Eye Clinic/Views/StockManagement/StockLedger.cshtml
@model Kamala_Eye_Clinic.Models.StockLedger

@{
    ViewBag.Title = "Stock Ledger";
    Layout = "~/Views/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-md-12 form-group">
            <div class="col-md-4">
                <div class="col-md-5">
                    @Html.LabelFor(model => model.itemname, htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-7">
                    @Html.DropDownListFor(model => model.itemname, Model.items, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.itemname, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-5">
                    @Html.LabelFor(model => model.unit, htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-7">
                    @Html.DropDownListFor(model => model.unit, Model.units, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.unit, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-5">
                    @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-7">
                    @Html.DropDownListFor(model => model.type, new SelectList(new[] { "Addtion", "Deduction" }), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-12 form-group">
            <div class="col-md-4">
                <div class="col-md-5">
                    @Html.LabelFor(model => model.qty, htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-7">
                    @Html.EditorFor(model => model.qty, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.qty, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-5">
                    @Html.LabelFor(model => model.openingqty, htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-7">
                    @Html.EditorFor(model => model.openingqty, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                    @Html.ValidationMessageFor(model => model.openingqty, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-5">
                    @Html.LabelFor(model => model.closingqty, htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-7">
                    @Html.EditorFor(model => model.closingqty, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                    @Html.ValidationMessageFor(model => model.closingqty, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-12 col-sm-12 form-group" align="center">
            <hr />
            @Html.HiddenFor(model => model.CMD)
            @if (Model.CMD == null)
                {
                <input type="submit" class="btn btn-default btn-info " value="Save" name="SubmitBtn" />
            }
            else
            {
                <input type="submit" class="btn btn-default btn-primary " value="Update" name="SubmitBtn" />
                @* <input type="submit" class="btn btn-default btn-danger" value="Delete" name="SubmitBtn" />*@
            }
            <input type="reset" class="btn btn-warning " value="Reset" />
        </div>
    </div>
}

Kamala Eye Clinic/Views/StockManagement/UOM.cshtml
@model Kamala_Eye_Clinic.Models.UOM

@{
    ViewBag.Title = "Unit Of Measurement";
    Layout = "~/Views/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row ">
            <div class="col-md-12 form-group">
                <div class="col-md-6">
                    <div class="col-md-5">
                        @Html.LabelFor(model => model.unitname, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.unitname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.unitname, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-12 form-group">
                <div class="col-md-6">
                    <div class="col-md-5">
                        @Html.LabelFor(model => model.uom, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.uom, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.uom, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-sm-12 form-group" align="center">
                <hr />
                @Html.HiddenFor(model => model.CMD)
                @if (Model.CMD == null)
                {
                    <input type="submit" class="btn btn-default btn-info " value="Save" name="SubmitBtn" />
                }
                else
                {
                    <input type="submit" class="btn btn-default btn-primary " value="Update" name="SubmitBtn" />
                    @* <input type="submit" class="btn btn-default btn-danger" value="Delete" name="SubmitBtn" />*@
                }
                <input type="reset" class="btn btn-warning " value="Reset" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("  Back to List", "ViewUOM","StockManagement",new { @class= "fa fa-arrow-circle-o-left btn btn-info btn-sm" })
</div>

Kamala Eye Clinic/Views/StockManagement/ViewItem.cshtml
@model System.Data.DataSet
@{
    ViewBag.Title = "Item";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">
    <div class="form-horizontal">
        <div class="col-lg-12">
            <div class="col-lg-4">
                <a class="btn btn-primary" href="~/StockManagement/Item"><i class="fa fa-plus"></i> &nbsp; Add New Item</a>
            </div>
        </div>
        <div class="col-lg-12">
            <hr />
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Item Id</th>
                            <th>Item Name</th>
                            <th>Unit</th>
                            <th>Rate</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @try
                        {
                            for (int i = 0; i <= Model.Tables[0].Rows.Count - 1; i++)
                            {
                                <tr>
                                    <td>@(i + 1)</td>
                                    <td>@Model.Tables[0].Rows[i]["itemid"]</td>
                                    <td>@Model.Tables[0].Rows[i]["itemname"]</td>
                                    <td>@Model.Tables[0].Rows[i]["unit"]</td>
                                    <td>@Model.Tables[0].Rows[i]["rate"]</td>
                                    <td>@Html.ActionLink("Edit", "ItemUpdate", new { itemid = Model.Tables[0].Rows[i]["itemid"] })</td>
                                </tr>
                            }
                        }
                        catch (Exception) { }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Kamala Eye Clinic/Views/StockManagement/ViewStockLeadger.cshtml
@model System.Data.DataSet
@{
    ViewBag.Title = "Stock Leadger";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">
    <div class="form-horizontal">      
        <div class="col-lg-12">
            <hr />
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Item Id</th>
                            <th>Item Name</th>
                            <th>Unit</th>
                            <th>Rate</th>
                            <th>Type</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @try
                        {
                            for (int i = 0; i <= Model.Tables[0].Rows.Count - 1; i++)
                            {
                                <tr>
                                    <td>@(i + 1)</td>
                                    <td>@Model.Tables[0].Rows[i]["transactionid"]</td>
                                    <td>@Model.Tables[0].Rows[i]["itemid"]</td>
                                    <td>@Model.Tables[0].Rows[i]["itemname"]</td>
                                    <td>@Model.Tables[0].Rows[i]["unit"]</td>
                                    <td>@Model.Tables[0].Rows[i]["rate"]</td>
                                    <td>@Model.Tables[0].Rows[i]["ttype"]</td>
                                    <td>@Html.ActionLink("Edit", "StockLedgerUpdate", new {transactionid = Model.Tables[0].Rows[i]["transactionid"] })</td>
                                </tr>
                            }
                        }
                        catch (Exception) { }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Kamala Eye Clinic/Views/StockManagement/ViewUOM.cshtml
@model System.Data.DataSet
@{
    ViewBag.Title = "Unit Of Measurement";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">
    <div class="form-horizontal">
        <div class="col-lg-12">
            <div class="col-lg-4">
                <a class="btn btn-primary" href="~/StockManagement/UOM"><i class="fa fa-plus"></i> &nbsp; Add New Unit</a>
            </div>
        </div>
        <div class="col-lg-12">
            <hr/>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Unit Id</th>
                            <th>Unit Name</th>
                            <th>Unit of Measurement</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @try
                        {
                            for (int i = 0; i <= Model.Tables[0].Rows.Count - 1; i++)
                            {
                                <tr>
                                    <td>@(i + 1)</td>
                                    <td>@Model.Tables[0].Rows[i]["unitid"]</td>
                                    <td>@Model.Tables[0].Rows[i]["unitname"]</td>
                                    <td>@Model.Tables[0].Rows[i]["uom"]</td>
                                    <td>@Html.ActionLink("Edit", "Update", new { unitid = Model.Tables[0].Rows[i]["unitid"] })</td>
                                </tr>
                            }
                        }
                        catch (Exception) { }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>