Kamala Eye Clinic/Models/AdviceMaster.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;

namespace Kamala_Eye_Clinic.Models
{
    public class AdviceMaster
    {
        public int hid { get; set; }
        public int adviceid { get; set; }

        [Required(ErrorMessage = "Advice is Required")]
        [Display(Name = "Advice Name:")]
        public string advicename { get; set; }

        [Display(Name = "Description:")]
        public string advicedescription { get; set; }

        public string createby { get; set; }

        public string updateby { get; set; }

        public string CMD { get; set; }

        public string[] PerformAction()
        {
            try
            {
                this.createby = this.updateby = HttpContext.Current.Session["UserName"].ToString();
                string xml = Common.ToXML(this);
                DBConnection con = new DBConnection();
                DataSet ds = con.ExecuteProcedure("SP_Advice", xml);
                return Common.CallbackMsg(ds);
            }
            catch (Exception e)
            {
                return new string[] { "Failed", e.Message };
            }
        }

        public AdviceMaster GetSingleAdvice(int adviceid)
        {
            this.CMD = "View1";
            this.adviceid = adviceid;
            string xml = Common.ToXML(this);
            DBConnection con = new DBConnection();
            DataSet ds = con.ExecuteProcedure("SP_Advice", xml);
            if (ds != null)
            {
                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    this.advicename = ds.Tables[0].Rows[i]["advicename"].ToString();
                    this.advicedescription = ds.Tables[0].Rows[i]["advicedescription"].ToString();
                }
            }
            return this;
        }

        public List<AdviceMaster> GetAllAdvice()
        {
            this.CMD = "View";
            this.hid = Convert.ToInt32(HttpContext.Current.Session["hospital"].ToString());
            string xml = Common.ToXML(this);
            DBConnection con = new DBConnection();
            DataSet ds = con.ExecuteProcedure("SP_Advice", xml);

            List<AdviceMaster> Advicelist = new List<AdviceMaster>();
            if (ds != null)
            {
                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    AdviceMaster ch = new AdviceMaster();
                    ch.adviceid = Convert.ToInt32(ds.Tables[0].Rows[i]["adviceid"].ToString());
                    ch.advicename = ds.Tables[0].Rows[i]["advicename"].ToString();
                    Advicelist.Add(ch);
                }
            }
            return Advicelist;
        }


    }
}

Kamala Eye Clinic/Models/CheckupMaster.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;

namespace Kamala_Eye_Clinic.Models
{
    public class CheckupMaster
    {
        public int hid { get; set; }
        public int checkupid { get; set; }

        [Required(ErrorMessage = "Checkup is Required")]
        [Display(Name = "Checkup Name:")]
        public string checkupname { get; set; }

        [Display(Name = "Description:")]
        public string checkupdescription { get; set; }

        public string createby { get; set; }

        public string updateby { get; set; }

        public string CMD { get; set; }

        public string[] PerformAction()
        {
            try
            {
                this.createby = this.updateby = HttpContext.Current.Session["UserName"].ToString();
                string xml = Common.ToXML(this);
                DBConnection con = new DBConnection();
                DataSet ds = con.ExecuteProcedure("SP_Checkup", xml);
                return Common.CallbackMsg(ds);
            }
            catch (Exception e)
            {
                return new string[] { "Failed", e.Message };
            }
        }

        public CheckupMaster GetSingleCheckup(int checkupid)
        {
            this.CMD = "View1";
            this.checkupid = checkupid;
            string xml = Common.ToXML(this);
            DBConnection con = new DBConnection();
            DataSet ds = con.ExecuteProcedure("SP_Checkup", xml);
            if (ds != null)
            {
                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    this.checkupname = ds.Tables[0].Rows[i]["checkupname"].ToString();
                    this.checkupdescription = ds.Tables[0].Rows[i]["checkupdescription"].ToString();
                }
            }
            return this;
        }

        public List<CheckupMaster> GetAllCheckup()
        {
            this.CMD = "View";
            this.hid = Convert.ToInt32(HttpContext.Current.Session["hospital"].ToString());
            string xml = Common.ToXML(this);
            DBConnection con = new DBConnection();
            DataSet ds = con.ExecuteProcedure("SP_Checkup", xml);

            List<CheckupMaster> Checkuplist = new List<CheckupMaster>();
            if (ds != null)
            {
                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    CheckupMaster ch = new CheckupMaster();
                    ch.checkupid = Convert.ToInt32(ds.Tables[0].Rows[i]["checkupid"].ToString());
                    ch.checkupname = ds.Tables[0].Rows[i]["checkupname"].ToString();
                    Checkuplist.Add(ch);
                }
            }
            return Checkuplist;
        }


    }
}

Kamala Eye Clinic/Controllers/TreatmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kamala_Eye_Clinic.Models;
using System.Data;

namespace Kamala_Eye_Clinic.Controllers
{
    [Sessionclass]
    public class TreatmentController : Controller
    {
        // GET: Treatment
       
        public ViewResult PresentingComplentsMaster()
        {
            PresentingComplentsMaster obj = new Models.PresentingComplentsMaster();
            return View(obj);
        }

        [HttpPost]
        public ActionResult PresentingComplentsMaster(PresentingComplentsMaster obj, string SubmitBtn)
        {
            obj.CMD = SubmitBtn == "Save" ? "Save" : SubmitBtn == "Update" ? "Update" : "Delete";
            switch (obj.CMD)
            {
                case "Save":
                    obj.hid = Convert.ToInt32(Session["hospital"].ToString());
                    string[] str = obj.PerformAction();
                    ViewBag.msg = str[1];
                    return RedirectToAction("PresentingComplentsDetails");
                case "Update":
                    string[] str1 = obj.PerformAction();
                    ViewBag.msg = str1[2];
                    return RedirectToAction("PresentingComplentsDetails");
                case "Delete":
                    string[] str2 = obj.PerformAction();
                    ViewBag.msg = str2[3];
                    return RedirectToAction("PresentingComplentsDetails");
                default:
                    return View(obj);
            }
        }

        public ViewResult PresentingComplentsMasterUpdate(int hid, int complentid)
        {
            PresentingComplentsMaster obj = new PresentingComplentsMaster();

            if (complentid > 0)
            {
                obj.CMD = "Update";
                obj.complentid = complentid;
                obj.hid = hid;
                obj = obj.GetSingleComplent(complentid);
            }
            return View("PresentingComplentsMaster", obj);
        }

        [HttpPost]
        public ActionResult PresentingComplentsMasterUpdate(PresentingComplentsMaster obj, string SubmitBtn)
        {
            PresentingComplentsMaster(obj, SubmitBtn);
            if (SubmitBtn == "Delete") return Redirect("~/Treatment/PresentingComplentsMaster");
            return View("PresentingComplentsMaster", obj);
        }

        public ViewResult PresentingComplentsDetails(PresentingComplentsMaster obj, string cmd)
        {
            DBConnection cn = new DBConnection();
            obj.CMD = "View";
            obj.hid = Convert.ToInt32(Session["hospital"].ToString());
            string xml = Common.ToXML(obj);
            DataSet dataset = cn.ExecuteProcedure("SP_Complent", xml);
            return View(dataset);
        }


        /***********************           Treatment History And Duration            *****************/
        public ViewResult HistoryMaster()
        {
            HistoryMaster obj = new Models.HistoryMaster();
            return View(obj);
        }

        [HttpPost]
        public ActionResult HistoryMaster(HistoryMaster obj, string SubmitBtn)
        {
            obj.CMD = SubmitBtn == "Save" ? "Save" : SubmitBtn == "Update" ? "Update" : "Delete";
            switch (obj.CMD)
            {
                case "Save":
                    obj.hid = Convert.ToInt32(Session["hospital"].ToString());
                    string[] str = obj.PerformAction();
                    ViewBag.msg = str[1];
                    return RedirectToAction("HistoryDetails");
                case "Update":
                    string[] str1 = obj.PerformAction();
                    ViewBag.msg = str1[2];
                    return RedirectToAction("HistoryDetails");
                case "Delete":
                    string[] str2 = obj.PerformAction();
                    ViewBag.msg = str2[3];
                    return RedirectToAction("HistoryDetails");
                default:
                    return View(obj);
            }
        }

        public ViewResult HistoryMasterUpdate(int hid, int historyid)
        {
            HistoryMaster obj = new HistoryMaster();

            if (historyid > 0)
            {
                obj.CMD = "Update";
                obj.historyid = historyid;
                obj.hid = hid;
                obj = obj.GetSingleHistory(historyid);
            }
            return View("HistoryMaster", obj);
        }

        [HttpPost]
        public ActionResult HistoryMasterUpdate(HistoryMaster obj, string SubmitBtn)
        {
            HistoryMaster(obj, SubmitBtn);
            if (SubmitBtn == "Delete") return Redirect("~/Treatment/HistoryMaster");
            return View("HistoryMaster", obj);
        }

        public ViewResult HistoryDetails(HistoryMaster obj, string cmd)
        {
            DBConnection cn = new DBConnection();
            obj.CMD = "View";
            obj.hid = Convert.ToInt32(Session["hospital"].ToString());
            string xml = Common.ToXML(obj);
            DataSet dataset = cn.ExecuteProcedure("SP_History", xml);
            return View(dataset);
        }

        /***********************                     Occupation                      *****************/
        public ViewResult OccupationMaster()
        {
            OccupationMaster obj = new Models.OccupationMaster();
            return View(obj);
        }

        [HttpPost]
        public ActionResult OccupationMaster(OccupationMaster obj, string SubmitBtn)
        {
            obj.CMD = SubmitBtn == "Save" ? "Save" : SubmitBtn == "Update" ? "Update" : "Delete";
            switch (obj.CMD)
            {
                case "Save":
                    obj.hid = Convert.ToInt32(Session["hospital"].ToString());
                    string[] str = obj.PerformAction();
                    ViewBag.msg = str[1];
                    return RedirectToAction("OccupationDetails");
                case "Update":
                    string[] str1 = obj.PerformAction();
                    ViewBag.msg = str1[2];
                    return RedirectToAction("OccupationDetails");
                case "Delete":
                    string[] str2 = obj.PerformAction();
                    ViewBag.msg = str2[3];
                    return RedirectToAction("OccupationDetails");
                default:
                    return View(obj);
            }
        }

        public ViewResult OccupationMasterUpdate(int hid, int occupationid)
        {
            OccupationMaster obj = new OccupationMaster();

            if (occupationid > 0)
            {
                obj.CMD = "Update";
                obj.occupationid = occupationid;
                obj.hid = hid;
                obj = obj.GetSingleOccupation(occupationid);
            }
            return View("OccupationMaster", obj);
        }

        [HttpPost]
        public ActionResult OccupationMasterUpdate(OccupationMaster obj, string SubmitBtn)
        {
            OccupationMaster(obj, SubmitBtn);
            if (SubmitBtn == "Delete") return Redirect("~/Treatment/OccupationMaster");
            return View("OccupationMaster", obj);
        }

        public ViewResult OccupationDetails(OccupationMaster obj, string cmd)
        {
            DBConnection cn = new DBConnection();
            obj.CMD = "View";
            obj.hid = Convert.ToInt32(Session["hospital"].ToString());
            string xml = Common.ToXML(obj);
            DataSet dataset = cn.ExecuteProcedure("SP_Occupation", xml);
            return View(dataset);
        }

        /*****************************                 Presenting Diagnosis           *************************/

        public ViewResult PresentingDiagnosisMaster()
        {
            PresentingDiagnosisMaster obj = new Models.PresentingDiagnosisMaster();
            return View(obj);
        }

        [HttpPost]
        public ActionResult PresentingDiagnosisMaster(PresentingDiagnosisMaster obj, string SubmitBtn)
        {
            obj.CMD = SubmitBtn == "Save" ? "Save" : SubmitBtn == "Update" ? "Update" : "Delete";
            switch (obj.CMD)
            {
                case "Save":
                    obj.hid = Convert.ToInt32(Session["hospital"].ToString());
                    string[] str = obj.PerformAction();
                    ViewBag.msg = str[1];
                    return RedirectToAction("PresentingDiagnosisDetails");
                case "Update":
                    string[] str1 = obj.PerformAction();
                    ViewBag.msg = str1[2];
                    return RedirectToAction("PresentingDiagnosisDetails");
                case "Delete":
                    string[] str2 = obj.PerformAction();
                    ViewBag.msg = str2[3];
                    return RedirectToAction("PresentingDiagnosisDetails");
                default:
                    return View(obj);
            }
        }

        public ViewResult PresentingDiagnosisMasterUpdate(int hid, int diagnosisid)
        {
            PresentingDiagnosisMaster obj = new PresentingDiagnosisMaster();

            if (diagnosisid > 0)
            {
                obj.CMD = "Update";
                obj.diagnosisid = diagnosisid;
                obj.hid = hid;
                obj = obj.GetSingleDiagnosis(diagnosisid);
            }
            return View("PresentingDiagnosisMaster", obj);
        }

        [HttpPost]
        public ActionResult PresentingDiagnosisMasterUpdate(PresentingDiagnosisMaster obj, string SubmitBtn)
        {
            PresentingDiagnosisMaster(obj, SubmitBtn);
            if (SubmitBtn == "Delete") return Redirect("~/Treatment/PresentingDiagnosisMaster");
            return View("PresentingDiagnosisMaster", obj);
        }

        public ViewResult PresentingDiagnosisDetails(PresentingDiagnosisMaster obj, string cmd)
        {
            DBConnection cn = new DBConnection();
            obj.CMD = "View";

Kamala Eye Clinic/Views/Treatment/AdviceDetails.cshtml
@model System.Data.DataSet
@{
    ViewBag.Title = "Advice Details";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">
    <div class="form-horizontal">
        <div class="col-lg-12">
            <div class="col-lg-4">
                <a class="btn btn-primary" href="~/Treatment/AdviceMaster"><i class="fa fa-plus"></i> &nbsp; Add New Advice</a>
            </div>
        </div>
        <div class="col-lg-12">
            <hr />
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Advice Id</th>
                            <th>Advice Name</th>
                            <th>Description</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @try
                        {
                            for (int i = 0; i <= Model.Tables[0].Rows.Count - 1; i++)
                            {
                                <tr>
                                    <td>@(i + 1)</td>
                                    <td>@Model.Tables[0].Rows[i]["adviceid"]</td>
                                    <td>@Model.Tables[0].Rows[i]["advicename"]</td>
                                    <td>@Model.Tables[0].Rows[i]["advicedescription"]</td>
                                    <td>@Html.ActionLink("Edit", "AdviceMasterUpdate", new { hid = Model.Tables[0].Rows[i][0], adviceid = Model.Tables[0].Rows[i][1] })</td>
                                </tr>
                            }
                        }
                        catch (Exception)
                        {
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Kamala Eye Clinic/Views/Treatment/AdviceMaster.cshtml
@model Kamala_Eye_Clinic.Models.AdviceMaster
@{
    ViewBag.Title = "Advice Master";
    Layout = "~/Views/_Layout.cshtml";
}
<div class="row">

    @if (ViewBag != null)
    {
        <label>@ViewBag.msg </label>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-lg-12 form-group">
                <div class="col-lg-6">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.advicename, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.EditorFor(model => model.advicename, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.advicename, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 form-group">
                <div class="col-lg-6">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.advicedescription, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.EditorFor(model => model.advicedescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.advicedescription, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-lg-12 form-group">
                <br />
                <div class="col-lg-6 form-group" align="center">
                    @Html.HiddenFor(model => model.CMD)
                    @if (Model.CMD == null)

                    {
                        <input type="submit" class="btn btn-default btn-info" value="Save" name="SubmitBtn" />
                    }
                    else
                    {
                        <input type="submit" class="btn btn-default btn-primary" value="Update" name="SubmitBtn" />
                        @* <input type="submit" class="btn btn-default btn-danger" value="Delete" name="SubmitBtn" />*@
                    }
                    <input type="reset" class="btn btn-warning" value="Reset" />
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("  Back to List", "AdviceDetails", "Treatment", new { @class = "fa fa-arrow-circle-o-left btn btn-info btn-sm" })
</div>

Kamala Eye Clinic/Views/Treatment/CheckupMaster.cshtml
@model Kamala_Eye_Clinic.Models.CheckupMaster
@{
    ViewBag.Title = "Checkup Master";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">

    @if (ViewBag != null)
    {
        <label>@ViewBag.msg </label>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-lg-12 form-group">
                <div class="col-lg-6">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.checkupname, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.EditorFor(model => model.checkupname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.checkupname, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 form-group">
                <div class="col-lg-6">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.checkupdescription, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.EditorFor(model => model.checkupdescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.checkupdescription, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-lg-12 form-group">
                <br />
                <div class="col-lg-6 form-group" align="center">
                    @Html.HiddenFor(model => model.CMD)
                    @if (Model.CMD == null)

                    {
                        <input type="submit" class="btn btn-default btn-info" value="Save" name="SubmitBtn" />
                    }
                    else
                    {
                        <input type="submit" class="btn btn-default btn-primary" value="Update" name="SubmitBtn" />
                        @* <input type="submit" class="btn btn-default btn-danger" value="Delete" name="SubmitBtn" />*@
                    }
                    <input type="reset" class="btn btn-warning" value="Reset" />
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("  Back to List", "CheckupDetails", "Treatment", new { @class = "fa fa-arrow-circle-o-left btn btn-info btn-sm" })
</div>

Kamala Eye Clinic/Views/Treatment/FundusMaster.cshtml
@model Kamala_Eye_Clinic.Models.FundusMaster
@{
    ViewBag.Title = "Fundus Master";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">

    @if (ViewBag != null)
    {
        <label>@ViewBag.msg </label>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-lg-12 form-group">
                <div class="col-lg-6">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.fundusname, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.EditorFor(model => model.fundusname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.fundusname, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 form-group">
                <div class="col-lg-6">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.fundusdescription, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.EditorFor(model => model.fundusdescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.fundusdescription, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-lg-12 form-group">
                <br />
                <div class="col-lg-6 form-group" align="center">
                    @Html.HiddenFor(model => model.CMD)
                    @if (Model.CMD == null)

                    {
                        <input type="submit" class="btn btn-default btn-info" value="Save" name="SubmitBtn" />
                    }
                    else
                    {
                        <input type="submit" class="btn btn-default btn-primary" value="Update" name="SubmitBtn" />
                        @* <input type="submit" class="btn btn-default btn-danger" value="Delete" name="SubmitBtn" />*@
                    }
                    <input type="reset" class="btn btn-warning" value="Reset" />
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("  Back to List", "FundusDetails", "Treatment", new { @class = "fa fa-arrow-circle-o-left btn btn-info btn-sm" })
</div>

Kamala Eye Clinic/Views/Treatment/HistoryMaster.cshtml
@model Kamala_Eye_Clinic.Models.HistoryMaster
@{
    ViewBag.Title = "History Master";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">

    @if (ViewBag != null)
    {
        <label>@ViewBag.msg </label>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-lg-12 form-group">
                <div class="col-lg-6">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.historyname, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.EditorFor(model => model.historyname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.historyname, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 form-group">
                <div class="col-lg-6">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.historydescription, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.EditorFor(model => model.historydescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.historydescription, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-lg-12 form-group">
                <br />
                <div class="col-lg-6 form-group" align="center">
                    @Html.HiddenFor(model => model.CMD)
                    @if (Model.CMD == null)

                    {
                        <input type="submit" class="btn btn-default btn-info" value="Save" name="SubmitBtn" />
                    }
                    else
                    {
                        <input type="submit" class="btn btn-default btn-primary" value="Update" name="SubmitBtn" />
                        @* <input type="submit" class="btn btn-default btn-danger" value="Delete" name="SubmitBtn" />*@
                    }
                    <input type="reset" class="btn btn-warning" value="Reset" />
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("  Back to List", "HistoryDetails", "Treatment", new { @class = "fa fa-arrow-circle-o-left btn btn-info btn-sm" })
</div>

Kamala Eye Clinic/Views/Treatment/OccupationMaster.cshtml
@model Kamala_Eye_Clinic.Models.OccupationMaster
@{
    ViewBag.Title = "Occupation Master";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">

    @if (ViewBag != null)
    {
        <label>@ViewBag.msg </label>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-lg-12 form-group">
                <div class="col-lg-6">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.occupationname, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.EditorFor(model => model.occupationname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.occupationname, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 form-group">
                <div class="col-lg-6">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.occupationdescription, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.EditorFor(model => model.occupationdescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.occupationdescription, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-lg-12 form-group">
                <br />
                <div class="col-lg-6 form-group" align="center">
                    @Html.HiddenFor(model => model.CMD)
                    @if (Model.CMD == null)

                    {
                        <input type="submit" class="btn btn-default btn-info" value="Save" name="SubmitBtn" />
                    }
                    else
                    {
                        <input type="submit" class="btn btn-default btn-primary" value="Update" name="SubmitBtn" />
                        @* <input type="submit" class="btn btn-default btn-danger" value="Delete" name="SubmitBtn" />*@
                    }
                    <input type="reset" class="btn btn-warning" value="Reset" />
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("  Back to List", "OccupationDetails", "Treatment", new { @class = "fa fa-arrow-circle-o-left btn btn-info btn-sm" })
</div>