Kamala Eye Clinic/Controllers/SisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kamala_Eye_Clinic.Models;
using System.Data;
using System.Data.SqlClient;

namespace Kamala_Eye_Clinic.Controllers
{
    [Sessionclass]
    public class SisterController : Controller
    {

        public ViewResult Registration()
        {
            SisterMaster obj = new SisterMaster();
            return View(obj);
        }
        public ViewResult Update(int sisterid)
        {
            SisterMaster obj = new SisterMaster();

            if (sisterid > 0)
            {
                obj.CMD = "Update";
                //obj = obj.GetSingleSister(sisterid);
                obj = obj.GetSingleSister(sisterid, Convert.ToInt32(Session["hospital"].ToString()));

            }
            return View("Registration", obj);
        }
        [HttpPost]
        public ActionResult Update(SisterMaster obj, string SubmitBtn)
        {
            Registration(obj, SubmitBtn);
            if (SubmitBtn == "Delete") return Redirect("~/Sister/SisterDetsils");
            return View("Registration", obj);
        }

        [HttpPost]
        public ActionResult Registration(SisterMaster obj, string SubmitBtn)
        {
            obj.CMD = SubmitBtn == "Save" ? "Save" : SubmitBtn == "Update" ? "Update" : "Delete";
            obj.hid = Convert.ToInt32(Session["hospital"].ToString());
            switch (obj.CMD)
            {
                case "Save":
                    string[] str = obj.PerformAction();
                    ViewBag.msg = str[1];
                    return View("Registration", obj);
                case "Update":
                    string[] str1 = obj.PerformAction();
                    ViewBag.msg = str1[2];
                    return View("Registration", obj);
                case "Delete":
                    string[] str2 = obj.PerformAction();
                    ViewBag.msg = str2[3];
                    return View("Registration", obj);
                default:
                    return View(obj);
            }

        }

        public ActionResult SisterDetails()
        {
            SisterMaster obj = new SisterMaster();
            DBConnection cn = new DBConnection();
            obj.CMD = "View";
            obj.hid = Convert.ToInt32(Session["hospital"].ToString());
            string xml = Common.ToXML(obj);
            DataSet dataset = cn.ExecuteProcedure("SP_SisterRegistration", xml);
            return View(dataset);
        }
        [HttpPost]
        public ActionResult SisterDetails(FormCollection form, string submitBtn)
        {
            switch (submitBtn)
            {
                case "Search":
                    SisterMaster obj = new Models.SisterMaster();
                    if (form["sid"] != "")
                    {
                        obj.sisterid = Convert.ToInt32(form["sid"]);
                    }
                    else
                    {
                        obj.fname = form["fname"];
                        obj.lname = form["lname"];
                    }

                    obj.CMD = "View1";
                    obj.hid = Convert.ToInt32(Session["hospital"].ToString());
                    string xml = Common.ToXML(obj);
                    DBConnection cn = new DBConnection();
                    DataSet dataset = cn.ExecuteProcedure("SP_SisterRegistration", xml);
                    return View(dataset);
                case "ViewAll":
                    return RedirectToAction("SisterDetails");
                default:
                    return View();
            }
        }
        public ActionResult SisterSelection()
        {
            return View();
        }
    }
}

Kamala Eye Clinic/Views/Sister/Registration.cshtml
@model Kamala_Eye_Clinic.Models.SisterMaster

@{
    ViewBag.Title = "Registration";
    Layout = "~/Views/_Layout.cshtml";
}
<div class="row">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form">
            <h4>
                Sister Registration : <span style="font-size:14px">
                    @if (ViewBag != null)
                    {
                        <label>@ViewBag.msg </label>
                    }
                </span>
            </h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="col-lg-12 form-group">
                <div class="col-lg-4">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.DropDownListFor(model => model.title, new SelectList(new[] { "MR.", "MS.", "MRS." }), new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 form-group">
                <div class="col-lg-4">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.fname, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.TextBoxFor(model => model.fname, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.fname, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.mname, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.TextBoxFor(model => model.mname, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.mname, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.lname, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.TextBoxFor(model => model.lname, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.lname, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 form-group">
                <div class="col-lg-4">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.contact, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.TextBoxFor(model => model.contact, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.contact, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.dob, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        <div class="input-group">
                            @Html.TextBoxFor(model => model.dob, new { @class = "form-control date", placeholder = "mm/dd/yyyy" })
                            <div class="input-group-addon">
                                <i class="fa fa-calendar">
                                </i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.birthplace, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.TextBoxFor(model => model.birthplace, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.birthplace, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 form-group">
                <div class="col-lg-4">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.TextBoxFor(model => model.age, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-4 ">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.DropDownListFor(model => model.gender, new SelectList(new[] { "Male", "Female", "Other" }), new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-4 ">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.maritalstatus, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.DropDownListFor(model => model.maritalstatus, new SelectList(new[] { "Maried", "Unmaried" }), new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.maritalstatus, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 form-group">
                <div class="col-lg-4 ">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.bloodgroup, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.DropDownListFor(model => model.bloodgroup, new SelectList(new[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }), new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.bloodgroup, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-4 ">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.sheight, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        <div class="input-group">
                            @Html.TextBoxFor(model => model.sheight, new { @class = "form-control" })
                            <div class="input-group-addon">
                                Cm.
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.sheight, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-4 ">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.sweight, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        <div class="input-group">
                            @Html.TextBoxFor(model => model.sweight, new { @class = "form-control" })
                            <div class="input-group-addon">
                                Kg.
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.sweight, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 form-group">
                <div class="col-lg-4 ">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.qualification, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-lg-7">
                        @Html.TextBoxFor(model => model.qualification, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.qualification, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 form-group">
                <div class="col-lg-12" align="center">
                    @Html.HiddenFor(model => model.CMD)
                    @if (Model.CMD == null)
                    {
                        <input type="submit" class="btn btn-default btn-info " value="Save" name="SubmitBtn" />
                    }
                    else
                    {
                        <input type="submit" class="btn btn-default btn-primary " value="Update" name="SubmitBtn" />
                        @* <input type="submit" class="btn btn-default btn-danger" value="Delete" name="SubmitBtn" />*@
                    }
                    <input type="reset" class="btn btn-warning " value="Reset" />
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("  Back to List", "SisterDetails", "Sister", new { @class = "fa fa-arrow-circle-o-left btn btn-info btn-sm" })
</div>

Kamala Eye Clinic/Views/Sister/SisterDetails.cshtml
@model System.Data.DataSet
@{
    ViewBag.Title = "SisterDetails";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">
    <div class="page-header">
        <h4>Sister Details</h4>
    </div>
    <form class="form-horizontal" action="/Sister/SisterDetails" method="post">
        <div class="col-lg-12">
            <div class="col-lg-4">
                <a class="btn btn-primary" href="~/Sister/Registration"><i class="fa fa-plus"></i> &nbsp; Add New Sister</a>
            </div>
        </div>

        <div class="col-lg-12 form-group">
            <hr />
            <div class="col-lg-3">
                <div class="col-lg-10">
                    <input class="form-control" name="sid" type="text" placeholder="Sister Id" />
                </div>
            </div>
            <div class="col-lg-1" align="center">
                <label class="control-label">OR</label>
            </div>
            <div class="col-lg-3" align="center">
                <div class="col-lg-10">
                    <input class="form-control" name="fname" type="text" placeholder="First Name" />
                </div>
            </div>
            <div class="col-lg-3" align="center">
                <div class="col-lg-10">
                    <input class="form-control" name="lname" type="text" placeholder="Last Name" />
                </div>
            </div>
            <div class="col-lg-1">
                <button class="btn btn-info" type="submit" name="submitBtn" value="Search">Search</button>
            </div>
            <div class="col-lg-1">
                <button class="btn btn-info" type="submit" id="viewall" name="submitBtn" value="ViewAll">View All</button>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Sister Id</th>
                            <th>Sister Name</th>
                            <th>Registration Date</th>
                            <th>Contact No </th>
                            <th>Age</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @try
                        {
                            for (int i = 0; i <= Model.Tables[0].Rows.Count - 1; i++)
                            {
                                <tr>
                                    <td>@(i + 1)</td>
                                    <td>@Model.Tables[0].Rows[i]["sisterid"]</td>
                                    <td>@Model.Tables[0].Rows[i]["fname"]&nbsp;&nbsp; @Model.Tables[0].Rows[i]["mname"] &nbsp;&nbsp; @Model.Tables[0].Rows[i]["lname"]</td>
                                    <td>@Model.Tables[0].Rows[i]["reg_dt"]</td>
                                    <td>@Model.Tables[0].Rows[i]["contact"]</td>
                                    <td>@Model.Tables[0].Rows[i]["age"]</td>
                                    <td>@Html.ActionLink("Edit", "Update", new { sisterid = Model.Tables[0].Rows[i][1] })</td>
                                </tr>
                            }
                        }
                        catch (Exception) { }
                    </tbody>
                </table>
            </div>
        </div>
    </form>
</div>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>